### PR TITLE
Runner-up: Consider compilations targeting embedded platforms

### PR DESCRIPTION
**Pull request by trueqbit**

### CODE REVIEW

**Comment by thelink2012** [comment]
Very nice. Just worried about the opt-out behavior since it changes the default behavior of the library for compilers not having feature test macros.

Maybe we can test whether the compiler supports feature test macros (through it's own compiler version macro), if so and `__cpp_[rtti|exception]` isn't defined, it means the `NO_[EXCEPTION|RTTI]` behaviour should be taken. If the compiler doesn't support test macros (either because of its version, or because it's an unknown compiler), it should let exceptions/rtti enabled by default.

I assume the compiler for the platform you are working on supports the test macros given your first PR, correct? So I suggest simply adding a check for the compiler version of such compiler. If it's over the version it supports test macros (i.e. including your version), follow the behaviour described above that would cause RTTI and exceptions to be disabled.

**Comment by trueqbit** [comment]
You probably mean you are worried about the explicit opt-in behavior when the test macros aren't supported...

Yes, of course it is possible to check for compiler-specifics. But I have taken a look at boost's config predefine machinery, and it's convoluted - there are so many compiler variants out there! And a standard feature test macro doesn't help a lot if compiler writers unfortunately don't adhere to the standard.

I changed it to only observe the feature test macros when compiling under Particle. Since I am new to micro controller programming myself, I can't be entirely sure whether this is still too broad and at the same time too narrow because we exclude many other frameworks for embedded programming **sigh**

Let me know what you think - since we have already the necessary basic improvements in place, I am also happy to remove defaulting ANY_IMPL_NO* and live with a fork!

Also, this PR #11 doesn't recognize the first commit I proposed in PR #8, that's why there are merge conflicts. Not sure whether I can reopen the former PR or need to create yet another one from an entirely new branch off current master!?

**Comment by thelink2012** [comment]
I think I managed to fix the conflicts from the web interface. I'm happy with the current approach, so merging in, thank you! :)

**Comment by trueqbit** [comment]
Hmm, this wasn't the correct approach - the commit from PR #8 has been lost.

**Comment by thelink2012** [comment]
It's ok, I migrated the changes from the first PR to the conflict resolution commit.

**Pull request merged**
